---
- name: CockroachDB Query and Testing
  hosts: crdb_servers
  gather_facts: true
  become: false  # Set to true if you need privilege escalation

  vars_files:
    - vars/crdb_common.yml
    - vars/crdb_query.yml
    # Uncomment the appropriate environment file:
    - vars/environments/dev.yml
    # - vars/environments/prod.yml

  tasks:
    # Basic connectivity and version check
    - name: Wait for CockroachDB to become available
      ansible.builtin.wait_for:
        port: "{{ crdb_listen_port }}"
        delay: "{{ crdb_wait_delay }}"
        timeout: "{{ crdb_wait_timeout }}"

    - name: Execute SQL statements
      cockroach_labs.cockroachdb.cockroachdb_query:
        host: "{{ crdb_host }}"
        ssl_mode: "{{ crdb_secure_mode }}"
        database: "{{ query_database_name }}"
        query: |
          {{ sample_queries.create_table }}
          {{ sample_queries.insert_sample }}
          {{ sample_queries.select_all }}
      register: sql_result

    - name: Display SQL execution result
      ansible.builtin.debug:
        var: sql_result
