---
- name: CockroachDB Setup and Management
  hosts: crdb_servers
  gather_facts: true
  become: false  # Set to true if you need privilege escalation

  vars_files:
    - vars/crdb_common.yml
    - vars/crdb_setup.yml
    # Uncomment the appropriate environment file:
    - vars/environments/dev.yml
    # - vars/environments/prod.yml

  tasks:
    # Basic connectivity and version check
    - name: Wait for CockroachDB to become available
      ansible.builtin.wait_for:
        port: "{{ crdb_listen_port }}"
        delay: "{{ crdb_wait_delay }}"
        timeout: "{{ crdb_wait_timeout }}"

    - name: Check CockroachDB version
      ansible.builtin.command: cockroach version
      register: cockroach_version
      ignore_errors: true
      changed_when: false

    - name: Debug - show CockroachDB version
      ansible.builtin.debug:
        var: cockroach_version.stdout_lines
      when: cockroach_version is success

    - name: Get CockroachDB info
      rpunt.cockroachdb.cockroachdb_info:
        host: "{{ crdb_host }}"
        user: "{{ crdb_user }}"
        ssl_mode: "{{ crdb_secure_mode }}"
        gather_subset: ['cluster', 'databases']
      register: crdb_info

    - name: Create a database
      rpunt.cockroachdb.cockroachdb_db:
        name: "{{ setup_database_name }}"
        state: present
        host: "{{ crdb_host }}"
        user: "{{ crdb_user }}"
        ssl_mode: "{{ crdb_secure_mode }}"
      register: db_creation

    - name: Display database creation result
      ansible.builtin.debug:
        var: db_creation

    - name: Create database user
      rpunt.cockroachdb.cockroachdb_user:
        name: "{{ setup_user_name }}"
        state: present
        host: "{{ crdb_host }}"
        ssl_mode: "{{ crdb_secure_mode }}"
      register: user_creation

    - name: Display user creation result
      ansible.builtin.debug:
        var: user_creation

    - name: Grant privileges to user
      rpunt.cockroachdb.cockroachdb_privilege:
        roles: "{{ setup_user_name }}"
        database: "{{ setup_database_name }}"
        on_type: database
        object_name: "{{ setup_database_name }}"
        privileges: "{{ setup_privileges }}"
        state: grant
        ssl_mode: "{{ crdb_secure_mode }}"
      register: grant_result

    - name: Display grant result
      ansible.builtin.debug:
        var: grant_result

    - name: Set a cluster parameter
      rpunt.cockroachdb.cockroachdb_parameter:
        profile: "revenue"
        custom_profiles: "{{ cockroach_profiles }}"
        ssl_mode: "{{ crdb_secure_mode }}"
      register: parameter_result

    - name: Display parameter result
      ansible.builtin.debug:
        var: parameter_result
